argo_embedding_url: https://apps.inside.anl.gov/argoapi/api/v1/resource/embed/
argo_stream_url: https://apps-dev.inside.anl.gov/argoapi/api/v1/resource/streamchat/
argo_url: https://apps-dev.inside.anl.gov/argoapi/api/v1/resource/chat/
host: 127.0.0.1
port: 8000
user: jplfaria
verbose: true